CREATE TABLE
  `patients` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `name` varchar(191) NOT NULL,
    `surname` varchar(191) NOT NULL,
    `gender` enum('M', 'F', 'N') NOT NULL,
    `fiscal_code` varchar(191) DEFAULT NULL,
    `email` varchar(191) DEFAULT NULL,
    `phone` varchar(191) DEFAULT NULL,
    `birthdate` date DEFAULT NULL,
    `birth_city_id` bigint(20) unsigned DEFAULT NULL,
    `birth_country_id` bigint(20) unsigned DEFAULT NULL,
    `birth_foreign_city` varchar(191) DEFAULT NULL,
    `residence_address` varchar(191) DEFAULT NULL,
    `residence_zipcode` varchar(191) DEFAULT NULL,
    `residence_city_id` bigint(20) unsigned DEFAULT NULL,
    `residence_country_id` bigint(20) unsigned DEFAULT NULL,
    `residence_foreign_city` varchar(191) DEFAULT NULL,
    `parent_id` bigint(20) unsigned DEFAULT NULL,
    `password` varchar(191) DEFAULT NULL,
    `token` varchar(191) DEFAULT NULL,
    `vip` tinyint(1) DEFAULT 0,
    `uid` varchar(191) DEFAULT NULL,
    `acquisition_channel_id` bigint(20) unsigned DEFAULT NULL,
    `partner_id` bigint(20) unsigned DEFAULT NULL,
    `company_id` bigint(20) unsigned DEFAULT NULL,
    `office_id` bigint(20) DEFAULT NULL,
    `note` text DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    `md5_to_bcrypt_changed_at` timestamp NULL DEFAULT NULL,
    `active` tinyint(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`),
    KEY `patients_birth_city_id_foreign` (`birth_city_id`),
    KEY `patients_birth_country_id_foreign` (`birth_country_id`),
    KEY `patients_residence_city_id_foreign` (`residence_city_id`),
    KEY `patients_residence_country_id_foreign` (`residence_country_id`),
    KEY `patients_parent_id_foreign` (`parent_id`),
    KEY `patients_acquisition_channel_id_foreign` (`acquisition_channel_id`),
    KEY `patients_partner_id_foreign` (`partner_id`),
    KEY `patients_company_id_foreign` (`company_id`),
    CONSTRAINT `patients_acquisition_channel_id_foreign` FOREIGN KEY (`acquisition_channel_id`) REFERENCES `acquisition_channels` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `patients_birth_city_id_foreign` FOREIGN KEY (`birth_city_id`) REFERENCES `geo_cities` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `patients_birth_country_id_foreign` FOREIGN KEY (`birth_country_id`) REFERENCES `geo_countries` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `patients_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `patients_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `patients` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `patients_partner_id_foreign` FOREIGN KEY (`partner_id`) REFERENCES `partners` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `patients_residence_city_id_foreign` FOREIGN KEY (`residence_city_id`) REFERENCES `geo_cities` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `patients_residence_country_id_foreign` FOREIGN KEY (`residence_country_id`) REFERENCES `geo_countries` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE = InnoDB AUTO_INCREMENT = 83114 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

CREATE TABLE
  `duties` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `office_id` bigint(20) unsigned DEFAULT NULL,
    `description` varchar(191) NOT NULL,
    `base_periodicity` int(11) DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `duties_office_id_foreign` (`office_id`),
    CONSTRAINT `duties_office_id_foreign` FOREIGN KEY (`office_id`) REFERENCES `offices` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 5692 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

  CREATE TABLE
  `examinations` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `description` varchar(191) DEFAULT NULL,
    `test_group_id` bigint(20) unsigned NOT NULL,
    `status` tinyint(1) NOT NULL DEFAULT 0,
    `confirmation_date` datetime DEFAULT NULL,
    `company_costs_calculated_at` timestamp NULL DEFAULT NULL,
    `no_show` tinyint(1) NOT NULL DEFAULT 0,
    `start_date` datetime NOT NULL,
    `end_date` datetime DEFAULT NULL,
    `user_id` bigint(20) unsigned NOT NULL,
    `assumption_id` bigint(20) unsigned NOT NULL,
    `session_id` bigint(20) unsigned DEFAULT NULL,
    `medical_history` text DEFAULT NULL,
    `result` enum(
      'Giudizio non espresso',
      'Idoneo',
      'Idoneo con prescrizioni',
      'Idoneo con limitazioni',
      'Idoneo con limitazioni e prescrizioni',
      'Non idoneo',
      'Non idoneo temporaneamente',
      'Non idoneo permanentemente',
      'Non previsto'
    ) DEFAULT NULL,
    `result_file` varchar(191) DEFAULT NULL,
    `yousign_request_id` varchar(255) DEFAULT NULL,
    `yousign_idoneity_id` varchar(255) DEFAULT NULL,
    `yousign_idoneity_employee_id` varchar(255) DEFAULT NULL,
    `is_signed` varchar(255) NOT NULL DEFAULT '0',
    `is_certified_signature` tinyint(1) NOT NULL DEFAULT 0,
    `result_file_date` varchar(191) DEFAULT NULL,
    `release_date` date DEFAULT NULL,
    `expiration_date` date DEFAULT NULL,
    `transmission_date` date DEFAULT NULL,
    `transmission_method` varchar(191) DEFAULT NULL,
    `prescription_to_company` text DEFAULT NULL,
    `prescription_to_employee` text DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    `note` text DEFAULT NULL,
    `result_file_employee` varchar(255) DEFAULT NULL,
    `result_file_medical_record` varchar(255) DEFAULT NULL,
    `yousign_medical_record_id` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `examinations_user_id_foreign` (`user_id`),
    KEY `examinations_assumption_id_foreign` (`assumption_id`),
    KEY `examinations_session_id_index` (`session_id`),
    CONSTRAINT `examinations_assumption_id_foreign` FOREIGN KEY (`assumption_id`) REFERENCES `assumptions` (`id`),
    CONSTRAINT `examinations_session_id_foreign` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`),
    CONSTRAINT `examinations_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 23990 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

  CREATE TABLE
  `examinations` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `description` varchar(191) DEFAULT NULL,
    `test_group_id` bigint(20) unsigned NOT NULL,
    `status` tinyint(1) NOT NULL DEFAULT 0,
    `confirmation_date` datetime DEFAULT NULL,
    `company_costs_calculated_at` timestamp NULL DEFAULT NULL,
    `no_show` tinyint(1) NOT NULL DEFAULT 0,
    `start_date` datetime NOT NULL,
    `end_date` datetime DEFAULT NULL,
    `user_id` bigint(20) unsigned NOT NULL,
    `assumption_id` bigint(20) unsigned NOT NULL,
    `session_id` bigint(20) unsigned DEFAULT NULL,
    `medical_history` text DEFAULT NULL,
    `result` enum(
      'Giudizio non espresso',
      'Idoneo',
      'Idoneo con prescrizioni',
      'Idoneo con limitazioni',
      'Idoneo con limitazioni e prescrizioni',
      'Non idoneo',
      'Non idoneo temporaneamente',
      'Non idoneo permanentemente',
      'Non previsto'
    ) DEFAULT NULL,
    `result_file` varchar(191) DEFAULT NULL,
    `yousign_request_id` varchar(255) DEFAULT NULL,
    `yousign_idoneity_id` varchar(255) DEFAULT NULL,
    `yousign_idoneity_employee_id` varchar(255) DEFAULT NULL,
    `is_signed` varchar(255) NOT NULL DEFAULT '0',
    `is_certified_signature` tinyint(1) NOT NULL DEFAULT 0,
    `result_file_date` varchar(191) DEFAULT NULL,
    `release_date` date DEFAULT NULL,
    `expiration_date` date DEFAULT NULL,
    `transmission_date` date DEFAULT NULL,
    `transmission_method` varchar(191) DEFAULT NULL,
    `prescription_to_company` text DEFAULT NULL,
    `prescription_to_employee` text DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    `note` text DEFAULT NULL,
    `result_file_employee` varchar(255) DEFAULT NULL,
    `result_file_medical_record` varchar(255) DEFAULT NULL,
    `yousign_medical_record_id` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `examinations_user_id_foreign` (`user_id`),
    KEY `examinations_assumption_id_foreign` (`assumption_id`),
    KEY `examinations_session_id_index` (`session_id`),
    CONSTRAINT `examinations_assumption_id_foreign` FOREIGN KEY (`assumption_id`) REFERENCES `assumptions` (`id`),
    CONSTRAINT `examinations_session_id_foreign` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`),
    CONSTRAINT `examinations_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 23990 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

  CREATE TABLE
  `examinations` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `description` varchar(191) DEFAULT NULL,
    `test_group_id` bigint(20) unsigned NOT NULL,
    `status` tinyint(1) NOT NULL DEFAULT 0,
    `confirmation_date` datetime DEFAULT NULL,
    `company_costs_calculated_at` timestamp NULL DEFAULT NULL,
    `no_show` tinyint(1) NOT NULL DEFAULT 0,
    `start_date` datetime NOT NULL,
    `end_date` datetime DEFAULT NULL,
    `user_id` bigint(20) unsigned NOT NULL,
    `assumption_id` bigint(20) unsigned NOT NULL,
    `session_id` bigint(20) unsigned DEFAULT NULL,
    `medical_history` text DEFAULT NULL,
    `result` enum(
      'Giudizio non espresso',
      'Idoneo',
      'Idoneo con prescrizioni',
      'Idoneo con limitazioni',
      'Idoneo con limitazioni e prescrizioni',
      'Non idoneo',
      'Non idoneo temporaneamente',
      'Non idoneo permanentemente',
      'Non previsto'
    ) DEFAULT NULL,
    `result_file` varchar(191) DEFAULT NULL,
    `yousign_request_id` varchar(255) DEFAULT NULL,
    `yousign_idoneity_id` varchar(255) DEFAULT NULL,
    `yousign_idoneity_employee_id` varchar(255) DEFAULT NULL,
    `is_signed` varchar(255) NOT NULL DEFAULT '0',
    `is_certified_signature` tinyint(1) NOT NULL DEFAULT 0,
    `result_file_date` varchar(191) DEFAULT NULL,
    `release_date` date DEFAULT NULL,
    `expiration_date` date DEFAULT NULL,
    `transmission_date` date DEFAULT NULL,
    `transmission_method` varchar(191) DEFAULT NULL,
    `prescription_to_company` text DEFAULT NULL,
    `prescription_to_employee` text DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    `note` text DEFAULT NULL,
    `result_file_employee` varchar(255) DEFAULT NULL,
    `result_file_medical_record` varchar(255) DEFAULT NULL,
    `yousign_medical_record_id` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `examinations_user_id_foreign` (`user_id`),
    KEY `examinations_assumption_id_foreign` (`assumption_id`),
    KEY `examinations_session_id_index` (`session_id`),
    CONSTRAINT `examinations_assumption_id_foreign` FOREIGN KEY (`assumption_id`) REFERENCES `assumptions` (`id`),
    CONSTRAINT `examinations_session_id_foreign` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`),
    CONSTRAINT `examinations_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 23990 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci
CREATE TABLE
  `examinations` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `description` varchar(191) DEFAULT NULL,
    `test_group_id` bigint(20) unsigned NOT NULL,
    `status` tinyint(1) NOT NULL DEFAULT 0,
    `confirmation_date` datetime DEFAULT NULL,
    `company_costs_calculated_at` timestamp NULL DEFAULT NULL,
    `no_show` tinyint(1) NOT NULL DEFAULT 0,
    `start_date` datetime NOT NULL,
    `end_date` datetime DEFAULT NULL,
    `user_id` bigint(20) unsigned NOT NULL,
    `assumption_id` bigint(20) unsigned NOT NULL,
    `session_id` bigint(20) unsigned DEFAULT NULL,
    `medical_history` text DEFAULT NULL,
    `result` enum(
      'Giudizio non espresso',
      'Idoneo',
      'Idoneo con prescrizioni',
      'Idoneo con limitazioni',
      'Idoneo con limitazioni e prescrizioni',
      'Non idoneo',
      'Non idoneo temporaneamente',
      'Non idoneo permanentemente',
      'Non previsto'
    ) DEFAULT NULL,
    `result_file` varchar(191) DEFAULT NULL,
    `yousign_request_id` varchar(255) DEFAULT NULL,
    `yousign_idoneity_id` varchar(255) DEFAULT NULL,
    `yousign_idoneity_employee_id` varchar(255) DEFAULT NULL,
    `is_signed` varchar(255) NOT NULL DEFAULT '0',
    `is_certified_signature` tinyint(1) NOT NULL DEFAULT 0,
    `result_file_date` varchar(191) DEFAULT NULL,
    `release_date` date DEFAULT NULL,
    `expiration_date` date DEFAULT NULL,
    `transmission_date` date DEFAULT NULL,
    `transmission_method` varchar(191) DEFAULT NULL,
    `prescription_to_company` text DEFAULT NULL,
    `prescription_to_employee` text DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    `note` text DEFAULT NULL,
    `result_file_employee` varchar(255) DEFAULT NULL,
    `result_file_medical_record` varchar(255) DEFAULT NULL,
    `yousign_medical_record_id` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `examinations_user_id_foreign` (`user_id`),
    KEY `examinations_assumption_id_foreign` (`assumption_id`),
    KEY `examinations_session_id_index` (`session_id`),
    CONSTRAINT `examinations_assumption_id_foreign` FOREIGN KEY (`assumption_id`) REFERENCES `assumptions` (`id`),
    CONSTRAINT `examinations_session_id_foreign` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`),
    CONSTRAINT `examinations_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 23990 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

CREATE TABLE
  `offices` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `is_main` tinyint(1) NOT NULL DEFAULT 0,
    `company_id` bigint(20) unsigned NOT NULL,
    `name` varchar(191) NOT NULL,
    `business_name` varchar(191) DEFAULT NULL,
    `description` varchar(191) DEFAULT NULL,
    `office_country_id` bigint(20) unsigned DEFAULT NULL,
    `italian_office_city_id` bigint(20) unsigned DEFAULT NULL,
    `foreign_office_city` varchar(191) DEFAULT NULL,
    `address` varchar(191) DEFAULT NULL,
    `zipcode` varchar(191) DEFAULT NULL,
    `allowed_employees` varchar(191) DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `offices_company_id_foreign` (`company_id`),
    KEY `offices_office_country_id_foreign` (`office_country_id`),
    KEY `offices_italian_office_city_id_foreign` (`italian_office_city_id`),
    CONSTRAINT `offices_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
    CONSTRAINT `offices_italian_office_city_id_foreign` FOREIGN KEY (`italian_office_city_id`) REFERENCES `geo_cities` (`id`),
    CONSTRAINT `offices_office_country_id_foreign` FOREIGN KEY (`office_country_id`) REFERENCES `geo_countries` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 1437 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

  CREATE TABLE
  `companies` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `business_name` varchar(191) NOT NULL,
    `name` varchar(191) NOT NULL,
    `legal_representative` varchar(191) DEFAULT NULL,
    `fiscal_code` varchar(191) NOT NULL,
    `vat_number` varchar(191) NOT NULL,
    `sdi_code` varchar(191) NOT NULL,
    `ateco_code` varchar(191) DEFAULT NULL,
    `pec` varchar(191) DEFAULT NULL,
    `company_code` varchar(191) NOT NULL,
    `company_type` tinyint(1) NOT NULL DEFAULT 1,
    `email` varchar(191) DEFAULT NULL,
    `address` varchar(191) DEFAULT NULL,
    `zipcode` varchar(191) DEFAULT NULL,
    `office_country_id` bigint(20) unsigned DEFAULT NULL,
    `italian_office_city_id` bigint(20) unsigned DEFAULT NULL,
    `foreign_office_city` varchar(191) DEFAULT NULL,
    `phone` varchar(191) DEFAULT NULL,
    `mobile_phone` varchar(191) DEFAULT NULL,
    `company_group_id` bigint(20) unsigned DEFAULT NULL,
    `payment_method_id` bigint(20) unsigned DEFAULT NULL,
    `administrative_alert` tinyint(1) NOT NULL DEFAULT 0,
    `examinations_room_available` tinyint(1) NOT NULL DEFAULT 0,
    `pricelist_visible` tinyint(1) NOT NULL DEFAULT 1,
    `note` mediumtext DEFAULT NULL,
    `site_enabled` int(11) NOT NULL DEFAULT 0,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    `ceased_at` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `companies_office_country_id_foreign` (`office_country_id`),
    KEY `companies_italian_office_city_id_foreign` (`italian_office_city_id`),
    KEY `companies_group_id_foreign` (`company_group_id`),
    KEY `companies_payment_method_id_foreign` (`payment_method_id`),
    CONSTRAINT `companies_group_id_foreign` FOREIGN KEY (`company_group_id`) REFERENCES `company_groups` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `companies_italian_office_city_id_foreign` FOREIGN KEY (`italian_office_city_id`) REFERENCES `geo_cities` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `companies_office_country_id_foreign` FOREIGN KEY (`office_country_id`) REFERENCES `geo_countries` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `companies_payment_method_id_foreign` FOREIGN KEY (`payment_method_id`) REFERENCES `payment_methods` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE = InnoDB AUTO_INCREMENT = 574 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

CREATE TABLE
  `assumptions` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `office_id` bigint(20) unsigned NOT NULL,
    `patient_id` bigint(20) unsigned NOT NULL,
    `duty_id` bigint(20) unsigned DEFAULT NULL,
    `duty_alias` varchar(191) DEFAULT NULL,
    `start_date` date NOT NULL,
    `end_date` date DEFAULT NULL,
    `note` text DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `assumptions_office_id_foreign` (`office_id`),
    KEY `assumptions_patient_id_foreign` (`patient_id`),
    KEY `assumptions_duty_id_foreign` (`duty_id`),
    CONSTRAINT `assumptions_duty_id_foreign` FOREIGN KEY (`duty_id`) REFERENCES `duties` (`id`),
    CONSTRAINT `assumptions_office_id_foreign` FOREIGN KEY (`office_id`) REFERENCES `offices` (`id`),
    CONSTRAINT `assumptions_patient_id_foreign` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 42357 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

  CREATE TABLE
  `users` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `name` varchar(191) NOT NULL,
    `surname` varchar(191) NOT NULL,
    `email` varchar(191) NOT NULL,
    `phone` varchar(191) DEFAULT NULL,
    `sign` longtext DEFAULT NULL,
    `password` varchar(191) NOT NULL,
    `status` int(11) NOT NULL DEFAULT 1,
    `two_factor_secret` text DEFAULT NULL,
    `two_factor_recovery_codes` text DEFAULT NULL,
    `partner_id` bigint(20) unsigned DEFAULT NULL,
    `send_notifications` tinyint(1) unsigned DEFAULT NULL,
    `email_verified_at` timestamp NULL DEFAULT NULL,
    `remember_token` varchar(100) DEFAULT NULL,
    `google_2fa_secret` varchar(128) DEFAULT NULL,
    `google_2fa_recovery_codes` text DEFAULT NULL,
    `site_enabled` int(11) NOT NULL DEFAULT 0,
    `mfa_enabled` tinyint(1) NOT NULL DEFAULT 0,
    `created_by` bigint(20) unsigned NOT NULL,
    `updated_by` bigint(20) unsigned DEFAULT NULL,
    `deleted_by` bigint(20) unsigned DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `users_email_unique` (`email`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 2116 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

  CREATE TABLE
  `risks` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `risk_correspondence_id` bigint(20) unsigned DEFAULT NULL,
    `description` varchar(191) NOT NULL,
    `risk_suggestion_id` int(11) DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `risks_risk_correspondence_id_foreign` (`risk_correspondence_id`),
    CONSTRAINT `risks_risk_correspondence_id_foreign` FOREIGN KEY (`risk_correspondence_id`) REFERENCES `risk_correspondences` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 15788 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

  CREATE TABLE
  `tests` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `description` varchar(191) NOT NULL,
    `component` varchar(191) NOT NULL,
    `alias` varchar(191) NOT NULL,
    `periodicity` int(11) NOT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 161 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci


CREATE TABLE
  `assumptions` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `office_id` bigint(20) unsigned NOT NULL,
    `patient_id` bigint(20) unsigned NOT NULL,
    `duty_id` bigint(20) unsigned DEFAULT NULL,
    `duty_alias` varchar(191) DEFAULT NULL,
    `start_date` date NOT NULL,
    `end_date` date DEFAULT NULL,
    `note` text DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `assumptions_office_id_foreign` (`office_id`),
    KEY `assumptions_patient_id_foreign` (`patient_id`),
    KEY `assumptions_duty_id_foreign` (`duty_id`),
    CONSTRAINT `assumptions_duty_id_foreign` FOREIGN KEY (`duty_id`) REFERENCES `duties` (`id`),
    CONSTRAINT `assumptions_office_id_foreign` FOREIGN KEY (`office_id`) REFERENCES `offices` (`id`),
    CONSTRAINT `assumptions_patient_id_foreign` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 42357 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

  CREATE TABLE
  `duty_has_risk` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `duty_id` bigint(20) unsigned NOT NULL,
    `risk_id` bigint(20) unsigned NOT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `duty_has_risk_duty_id_foreign` (`duty_id`),
    KEY `duty_has_risk_risk_id_foreign` (`risk_id`),
    CONSTRAINT `duty_has_risk_duty_id_foreign` FOREIGN KEY (`duty_id`) REFERENCES `duties` (`id`),
    CONSTRAINT `duty_has_risk_risk_id_foreign` FOREIGN KEY (`risk_id`) REFERENCES `risks` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 15788 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

  CREATE TABLE
  `duties` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `office_id` bigint(20) unsigned DEFAULT NULL,
    `description` varchar(191) NOT NULL,
    `base_periodicity` int(11) DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `duties_office_id_foreign` (`office_id`),
    CONSTRAINT `duties_office_id_foreign` FOREIGN KEY (`office_id`) REFERENCES `offices` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 5692 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

  CREATE TABLE
  `offices` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `is_main` tinyint(1) NOT NULL DEFAULT 0,
    `company_id` bigint(20) unsigned NOT NULL,
    `name` varchar(191) NOT NULL,
    `business_name` varchar(191) DEFAULT NULL,
    `description` varchar(191) DEFAULT NULL,
    `office_country_id` bigint(20) unsigned DEFAULT NULL,
    `italian_office_city_id` bigint(20) unsigned DEFAULT NULL,
    `foreign_office_city` varchar(191) DEFAULT NULL,
    `address` varchar(191) DEFAULT NULL,
    `zipcode` varchar(191) DEFAULT NULL,
    `allowed_employees` varchar(191) DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `offices_company_id_foreign` (`company_id`),
    KEY `offices_office_country_id_foreign` (`office_country_id`),
    KEY `offices_italian_office_city_id_foreign` (`italian_office_city_id`),
    CONSTRAINT `offices_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
    CONSTRAINT `offices_italian_office_city_id_foreign` FOREIGN KEY (`italian_office_city_id`) REFERENCES `geo_cities` (`id`),
    CONSTRAINT `offices_office_country_id_foreign` FOREIGN KEY (`office_country_id`) REFERENCES `geo_countries` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 1437 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

  CREATE TABLE
  `risk_has_test` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `risk_id` bigint(20) unsigned NOT NULL,
    `test_id` bigint(20) unsigned NOT NULL,
    `periodicity` int(11) DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `risk_has_test_risk_id_foreign` (`risk_id`),
    KEY `risk_has_test_test_id_foreign` (`test_id`),
    CONSTRAINT `risk_has_test_risk_id_foreign` FOREIGN KEY (`risk_id`) REFERENCES `risks` (`id`),
    CONSTRAINT `risk_has_test_test_id_foreign` FOREIGN KEY (`test_id`) REFERENCES `tests` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 18512 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci

  CREATE TABLE
  `examination_details` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `examination_id` bigint(20) unsigned NOT NULL,
    `test_id` bigint(20) unsigned NOT NULL,
    `test_group_id` bigint(20) unsigned DEFAULT NULL,
    `component_name` varchar(255) DEFAULT NULL,
    `json` longtext DEFAULT NULL,
    `start_date` datetime DEFAULT NULL,
    `end_date` datetime DEFAULT NULL,
    `user_id` bigint(20) unsigned DEFAULT NULL,
    `executor_id` bigint(20) unsigned DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    `invoiced_at` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `examination_details_examination_id_foreign` (`examination_id`),
    KEY `examination_details_test_id_foreign` (`test_id`),
    KEY `examination_details_test_group_id_foreign` (`test_group_id`),
    KEY `examination_details_user_id_foreign` (`user_id`),
    KEY `examination_details_executor_id_foreign` (`executor_id`),
    CONSTRAINT `examination_details_examination_id_foreign` FOREIGN KEY (`examination_id`) REFERENCES `examinations` (`id`),
    CONSTRAINT `examination_details_executor_id_foreign` FOREIGN KEY (`executor_id`) REFERENCES `executors` (`id`),
    CONSTRAINT `examination_details_test_group_id_foreign` FOREIGN KEY (`test_group_id`) REFERENCES `test_groups` (`id`),
    CONSTRAINT `examination_details_test_id_foreign` FOREIGN KEY (`test_id`) REFERENCES `tests` (`id`),
    CONSTRAINT `examination_details_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 307637 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci